### ISSUE TITLE
Handling datatypes

### ISSUE THREAD

**Issue by ghost** [PrismarineJS/bedrock-protocol#1]
Here's a list of datatypes ProtoDef doesn't handle

These I suspect are doable:
- [x] int
- [x] long
- [x] byte
- [x] short
- [x] byte_array
- [x] string
- [x] float
- [x] uuid
- [x] vector3

These may take some more work and we have to take a look at MiNET
- [x] slot
- [x] metadatadictionary
- [x] entitylocations
- [x] blockrecords
- [x] records
- [x] playerattributes
- [x] playerrecords
- [x] blockcoordinates
- [x] entitymotions
- [x] itemstacks
- [x] metadataints
- [x] recipes
- [x] nbt
- [x] skin

**Comment by ghost** [comment]
This is what I've found so far
https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Net/MCPE%20Protocol%20Documentation.md this is pretty good for some datatypes 

https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Utils/Vector3.cs `vector3`
https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Utils/Nbt.cs `nbt`

OFFLINE_MESSAGE_DATA_ID is always 

```
byte[]
{ 0x00, 0xff, 0xff, 0x00, 0xfe, 0xfe, 0xfe, 0xfe, 0xfd, 0xfd, 0xfd, 0xfd, 0x12, 0x34, 0x56, 0x78 }
```

https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Net/UUID.cs#L57 `uuid` this seems to be the format
The same string appears here: https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/utils/UUID.php#L95

**EDIT**: RakNet is now handled in [node-raknet](https://github.com/mhsjlw/node-raknet) you don't need OFFLINE_MESSAGE_DATA_ID as it's RakNet's magic

**Comment by ghost** [comment]
Also, for 0.14 the current protocol version is 45

**Comment by mhsjlw** [comment]
Not sure why I didn't see this earlier, but OFFLINE_MESSAGE_DATA_ID is actually RakNet's magic.
