### ISSUE TITLE
createClient parameter "profilesFolder" not working as expected

### ISSUE THREAD

**Issue by LucienHH** [PrismarineJS/bedrock-protocol#104]
**Expected Behavior**
Creating a client with the parameter profilesFolder should store cached authentication tokens to that path.

**Observed Behavior**
Authentication tokens do get cached to the given path however after restarting the application da39a3_live-cache.json gets cleared to empty brackets `{}` and login needs to be verified once again.

**Steps to Reproduce**
1) Create a client with a path

```
bedrock.createClient({
	host: ip,
	port, 
	offline: false,
	authTitle: '00000000441cc96b',
	profilesFolder: './cache',
	skipPing: true,
	onMsaCode: log => {
		console.log(log);
	},
});
```

2) Authenticate with the given code and then observe that the tokens have been cached.

3) Restart the application and you will be asked to authenticate again and da39a3_live-cache.json will be empty brackets `{}`

**Comment by extremeheat** [comment]
Holding off on a fix for this until we separate the auth to its own lib.

**Comment by extremeheat** [comment]
@kashalls this should be working in pauth right? Do you think you would be able to open a PR for it here? The relevant files are under src/client if you want.

**Comment by kashalls** [comment]
> @kashalls this should be working in pauth right? Do you think you would be able to open a PR for it here? The relevant files are under src/client if you want.

I would need to make another PR for p-auth as the current live implementation does not cache. This is due to to because we haven't figured out if caching the public key is a good idea or not.

**Comment by extremeheat** [comment]
The live implementation doesn’t cache? AFAIK it’s just the multiplayer.minecraft.net API token that we don’t cache. The xbox/msa tokens should still be cached.

**Comment by extremeheat** [comment]
@LucienHH can you verify if this is still an issue? Should have been fixed in prismarine-auth

**Comment by LucienHH** [comment]
@extremeheat Just tested and is now working on the build from main. Nice work!
