### ISSUE TITLE
Client/Server testing

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/bedrock-protocol#11]
Find a server (and/or client) mcpe implementation we can run on circle ci (ie not pocketmine, too annoying to install) and test against it

**Comment by rom1504** [comment]
@mhsjlw is saying https://github.com/Nukkit/Nukkit can work for this. Got to make sure it's up to date and all

**Comment by ghost** [comment]
As of right now, the client would only function on a server that doesn't use encryption/JWT verification (it's also not updated yet :smile:
i.e.: pmmp/PocketMine-MP

**Comment by ghost** [comment]
Requires #7

**Comment by roblabla** [comment]
Would it be possible to use libminecraft.so to run an official server, I wonder ?

**Comment by ghost** [comment]
Yep, it's not just not easy... I've been working on this for a while but it's impossible to keep up with the updates it was based off of repurposing https://github.com/MCMrARM/mcpelauncher-linux (see the server branch) but it got out of hand pretty quick. Anyway, I think getting the client to actual work first connecting to a server off of your phone is probably a priority before we try to automate testing

**Comment by extremeheat** [comment]
Can now be done with the native server binaries. 

A bedrock-wrap can be written similar to node-minecraft-wrap. See https://github.com/xrnoz/bedrock-server for existing scripts that do this. Then we can update + test on ci.

**Comment by extremeheat** [comment]
Fixed in master for vanilla server, but testing some of the used popular 3rd party servers (PocketMine, Nukkit) is a good idea. I'm not sure if we should test them in master though, maybe only in PRs to not be constrained by bugs in other 3rd party things.

**Comment by u9g** [comment]
> Fixed in master for vanilla server, but testing some of the used popular 3rd party servers (PocketMine, Nukkit) is a good idea. I'm not sure if we should test them in master though, maybe only in PRs to not be constrained by bugs in other 3rd party things.

I don’t think its a problem, we can always go to them to open an issue

**Comment by rom1504** [comment]
This is mostly done
Let's reopen some more precise issues if needed
