### ISSUE TITLE
move protocol.json to mcdata

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/bedrock-protocol#12]
It's getting ready for minecraft-data inclusion.

See https://github.com/PrismarineJS/minecraft-data/issues/65

The visualizer at http://prismarinejs.github.io/minecraft-data/?d=protocol is kind of specific to the mcpc protocol and for it to visualize stuff properly, https://github.com/PrismarineJS/minecraft-data/issues/123 has to be fixed.

**Comment by ghost** [comment]
done in #13 .
