### ISSUE TITLE
ParamAters or paramEters?

### ISSUE THREAD

**Issue by MarsRon** [PrismarineJS/bedrock-protocol#135]
# ParamAters or paramEters?

While poking around with this library, I noticed that there are 2 different spellings for parameters: param***e***ter and param***a***ter. I'm not sure if this is a typo or intentional naming, but I'm sure that there is inconsistency throughout the entire library. Some comments use param***e***ters while other comments, and all code use param***a***ters. It also applies to [the API documentation](https://minecraft-data.prismarine.js.org/?v=bedrock_1.17.10&d=protocol).

## Steps to Reproduce
Search through the project and [the API documentation](https://minecraft-data.prismarine.js.org/?v=bedrock_1.17.10&d=protocol) using `parameter` and `paramater`.

Please do let me know if this is intentional or not. Thanks.

**Comment by rom1504** [comment]
Fix blocked by migration to Minecraft data

**Comment by extremeheat** [comment]
open for PR in https://github.com/PrismarineJS/minecraft-data/tree/master/data/bedrock

**Comment by rom1504** [comment]
Hi @MarsRon we're using Minecraft data now, do you want to re-open your PR there ?

**Comment by MarsRon** [comment]
> Hi @MarsRon we're using Minecraft data now, do you want to re-open your PR there ?

Will do, thanks.
