### ISSUE TITLE
0.15 support

### ISSUE THREAD

**Issue by ghost** [PrismarineJS/bedrock-protocol#14]
it's a work in progress, it's being done in the `realms` branch here's what we've got todo
- [x] finish new 0.15 packet updates
- [x] decode JWT in the login packet
- [x] fe packet body encryption with incremental ECDH

i'm probably missing a few things, but once we've got the protocol fixed, we'll merge it into mc-data and use it in the release

**Comment by rom1504** [comment]
About encryption:

> 13:54 `<rom1504>` currently it's raknet parser that parse all mcpe packets
> 13:54 `<rom1504>` we just pass it mcpe packets as custom packets
> 13:55 `<rom1504>` https://github.com/PrismarineJS/minecraft-data/blob/master/data/pe/0.14/protocol.json#L562 here we'll just put a restBuffer instead of mcpe_packet
> 13:55 `<rom1504>` and then we'll handle the parsing with a different parser

**Comment by rom1504** [comment]
also see https://confluence.yawk.at/display/PEPROTOCOL/Encryption

**Comment by ghost** [comment]
#15 helped out with ECDH

**Comment by rom1504** [comment]
Ok well I'm pretty sure we have the secret key wrong. We're doing the decryption right since it's passing the tests.

**Comment by rom1504** [comment]
I think I found a pb. In the server to client handshake packet we need to provide "  Base64-X509-encoded ECC public key of the server"
That means in the same format we are getting it. we're just doing `ec.getPublicKey('base64')` currently : that won't work.

**Comment by rom1504** [comment]
ok it works.
Remaining:
- [x] have a slicer stream to remove the checksum (like https://github.com/yorkie/stream-slice but let's actually check if the checksum fits)
- [x] pipe that to the parser stream
- [x] listen on the parser stream and emit the correct events to client

Then it should work with no API breakage.

**Comment by rom1504** [comment]
Okay I did that. Problem is I'm getting a batch with `78 da 63 60 60 60 64 01 00 00 0b 00 06` which corresponds to `00 00 00 01 04` which doesn't make any sense.
So I'm not sure what is going on.

**Comment by ghost** [comment]
All packets are length prefixed (thanks shoghicp) and magic no longer has the long, it is just the 0x04 which you are receiving

**Comment by rom1504** [comment]
Ok the server side of this works. Missing : client side.
In order to do it without copy pasting everything, try to put some of it in a common file. (Might be a client.js)

**Comment by rom1504** [comment]
Also I think we can have multiple version support like nmp.

**Comment by ghost** [comment]
Agreed

**Comment by rom1504** [comment]
So after looking at https://github.com/mhsjlw/pocket-minecraft-protocol/pull/16/files . I think the best way to have multiple protocol support is to have plugins in createServer that we can easily disable/enable depending on the version. (like nmp currently has for the client side)

**Comment by filfat** [comment]
+1

**Comment by hedgehog1029** [comment]
Clearly this hasn't been touched for a couple of months, but I'm getting some odd behaviour, including an assertion failure from `assert.equal(checksum.toString("hex"),computedCheckSum.toString("hex"));` obviously because the checksums are different. To even get to that line I had to resolve some issues with `decode2.extraData` not even existing in the second chain, possibly due to it being removed. Also note that if you're not signed into XBOX Live, it fails even earlier, missing `parsed.data.chain.chain[1]` (only `chain[0]` exists).
Could someone more adept with the MCPE protocol than me help?

**Comment by ghost** [comment]
Yeah, the reason why this pull request hasn't been merged and this issue hasn't been closed is because all of this stuff was hacked up in a couple of days. Due to our RakNet library's lack of reliability, lots of this stuff just doesn't work because we don't have any motivation to put forth the effort to fix it.

Yes, we don't support clients that don't use XBOX Live, that's an easy fix, just check if the public key is in the chain. Users that don't use XBOX Live shouldn't have encryption. The assertion fails because the checksums are different, this is because you aren't even using the correct public key, you must be using a different key from an earlier JWT (I explained above that XBOX Live is needed for encryption).

Unfortunately, you're on your own for a while as no more work will be put into the project due to lack of demand.

**Comment by ghost** [comment]
#18
