### ISSUE TITLE
ECDH support

### ISSUE THREAD

**Issue by roblabla** [PrismarineJS/bedrock-protocol#15]
some code : 

``` js
var crypto = require('crypto');
var Ber = require('asn1').Ber;

const pubKeyStr = "MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEDEKneqEvcqUqqFMM1HM1A4zWjJC+I8Y+aKzG5dl+6wNOHHQ4NmG2PEXRJYhujyodFH+wO0dEr4GM1WoaWog8xsYQ6mQJAC0eVpBM96spUB1eMN56+BwlJ4H3Qx4TAvAs";

var reader = new Ber.Reader(new Buffer(pubKeyStr, "base64"));
reader.readSequence();
reader.readSequence();
reader.readOID(); // Hey, I'm an elliptic curve
reader.readOID(); // This contains the curve type, could be useful

// The first byte is unused, it contains the "number of unused bits in last octet"
// The pubKey should start at "04" which signifies it is an "uncompressed" public key.
var pubKey = new Buffer(reader.readString(Ber.BitString, true)).slice(1);

// It'd be better to get this from the curve type OID
var server = crypto.createECDH('secp384r1');
server.generateKeys();
console.log(server.computeSecret(pubKey));
```

**Comment by roblabla** [comment]
Just want to do a  quick writeup/rant of how I came up with this.

I was presented with the following problem : Generate an ECDH with the given pubKey :

```
MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEDEKneqEvcqUqqFMM1HM1A4zWjJC+I8Y+aKzG5dl+6wN
OHHQ4NmG2PEXRJYhujyodFH+wO0dEr4GM1WoaWog8xsYQ6mQJAC0eVpBM96spUB1eMN56+Bwl
J4H3Qx4TAvAs
```

The pubKey looks very much like base64, and I was originally told the curve was 'sect239k1' (this turned out to be wrong, more on this later). So thinking "this can't be too complicated", I went ahead and wrote the fairly innocuous code :

``` js
var crypto = require('crypto');
var server = crypto.createECDH('sect239k1');
server.generateKeys();
console.log(server.computeSecret(new Buffer(pubKeyStr, 'base64')));
```

Bingo, that works ! Not. This errors out with the totally unhelpful message "Error: Failed to translate Buffer to a EC_POINT". Derp.

After looking up the error in the NodeJS source code, and being told this pubKey is a x509 base64 key (whatever that means), I suppose the problem is that the key isn't in the format OpenSSL expects. NodeJS source code tells me the error happens in the openssl function EC_POINT_oct2point. The man of that function is incredibly unhelpful : 

```
An EC_POINT structure represents a point on a curve.
[...] (Like, a few hundred lines)
The functions EC_POINT_point2oct(), EC_POINT_oct2point(), EC_POINT_point2bn(),
EC_POINT_bn2point(), EC_POINT_point2hex() and EC_POINT_hex2point() convert from and to
EC_POINTs for the formats: octet, BIGNUM and hexadecimal respectively.
```

That was helpful... Still, I have a hunch that it expects some pretty raw data, and doesn't accept whatever container format we're sending to it. A google later, I discover x509 is just a fancy name for ASN1 these days, so I summon lapo.it to the rescue.

https://lapo.it/asn1js/#3076301006072A8648CE3D020106052B81040022036200040C42A77AA12F72A52AA8530CD47335038CD68C90BE23C63E68ACC6E5D97EEB034E1C74383661B63C45D125886E8F2A1D147FB03B4744AF818CD56A1A5A883CC6C610EA6409002D1E56904CF7AB29501D5E30DE7AF81C252781F7431E1302F02C

This looks like what we want. We have a first OID telling us it's an elliptic curve pubkey, a second OID giving us the curve type (... Hey guys, you gave me the wrong curve !?! it's actually secp384r1), and a bitstring. Well, that wasn't too hard. Taking that bitstring and feeding it to crypto should do the trick, right ?

``` js
var crypto = require('crypto');
var Ber = require('asn1').Ber;

var reader = new Ber.Reader(new Buffer(pubKeyStr, "base64"));
reader.readSequence();
reader.readSequence();
reader.readOID(); // Hey, I'm an elliptic curve
reader.readOID(); // This contains the curve type, could be useful
var pubKey = reader.readString(Ber.BitString, true);
var server = crypto.createECDH('secp384r1');
server.generateKeys();
console.log(server.computeSecret(pubKey));
```

That ought to work, right ? Right ? Still nope. With the same goddamn error. Great. This is usually the time where I start reading OpenSSL implementation, which usually equate to giving up. But not this time. I decide to google up "1.3.132.0.34 bitstring" in hopes of having a real description of what that bitstring is. There, I find a (pretty random and completely unrelated) IETF draft (https://tools.ietf.org/html/draft-solinas-suiteb-cert-profile-00), which for some reason explain what that bitstring is : 

```
First byte is 0x00 for number of unused bits in last octet; second byte is 
0x04 to denote uncompressed format. Followed by 384-bit x-coordinate and
384-bit y-coordinate.
```

I naively try to slice the 2 first bytes but that doesn't work. Then I notice the interesting bit : "0x04 to denote uncompressed format". That rings a bell. When we do `ecdh.getPublicKey()`, we can specify its format between 'compressed', 'uncompressed' and 'hybrid'. The default being uncompressed. And after trying it a few times, the output always start with, you guessed it `0x04`. Oh I'm going to feel dirty.

``` js
var crypto = require('crypto');
var Ber = require('asn1').Ber;

var reader = new Ber.Reader(new Buffer(pubKeyStr, "base64"));
reader.readSequence();
reader.readSequence();
reader.readOID(); // Hey, I'm an elliptic curve
reader.readOID(); // This contains the curve type, could be useful
var pubKey = reader.readString(Ber.BitString, true).slice(1);
var server = crypto.createECDH('secp384r1');
server.generateKeys();
console.log(server.computeSecret(pubKey));
```

Success !

Morale of the story : Crypto is overly complicated for your lambda dev.

**Comment by rom1504** [comment]
I'm trying to figure out whether I can still make the unit test work. Trying this:

``` js
var crypto = require('crypto');
var Ber = require('asn1').Ber;

const pubKeyStr = "MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEDEKneqEvcqUqqFMM1HM1A4zWjJC+I8Y+aKzG5dl+6wNOHHQ4NmG2PEXRJYhujyodFH+wO0dEr4GM1WoaWog8xsYQ6mQJAC0eVpBM96spUB1eMN56+BwlJ4H3Qx4TAvAs";

var reader = new Ber.Reader(new Buffer(pubKeyStr, "base64"));
reader.readSequence();
reader.readSequence();
reader.readOID(); // Hey, I'm an elliptic curve
reader.readOID(); // This contains the curve type, could be useful

// The first byte is unused, it contains the "number of unused bits in last octet"
// The pubKey should start at "04" which signifies it is an "uncompressed" public key.
var pubKey = new Buffer(reader.readString(Ber.BitString, true)).slice(1);

// It'd be better to get this from the curve type OID
var server = crypto.createECDH('secp384r1');
//server.generateKeys();
server.setPrivateKey("MB8CAQAwEAYHKoZIzj0CAQYFK4EEACIECDAGAgEBBAEB","base64");
console.log(server.computeSecret(pubKey,"binary","base64"));
```

And it returns `tyTWXBcQbn1VyMMTN5LedkUpwSj6++E08Z9uyveHYPlF5BVMIMdHLiTuhNX45WFn` instead of `DEKneqEvcqUqqFMM1HM1A4zWjJC+I8Y+aKzG5dl+6wNOHHQ4NmG2PEXRJYhujyod`, not sure why.

Edit: maybe passing a PKCS8 key requires some more work. (I'm talking about the first unit test there https://confluence.yawk.at/display/PEPROTOCOL/Encryption )

edit2: according to https://tools.ietf.org/html/rfc5208 pkcs8 seems to be asn1 too

edit3: https://github.com/rzcoder/node-rsa/blob/master/src/formats/pkcs8.js

edit4: okay maybe making work this test with that data is not that important, we can make new data in a format more like node I guess.

edit5:
Working "test" with my own private key : (which indeed isn't the same format as yawkat one)

``` js
var crypto = require('crypto');
var Ber = require('asn1').Ber;
var assert = require('assert');

const pubKeyStr = "MHYwEAYHKoZIzj0CAQYFK4EEACIDYgAEDEKneqEvcqUqqFMM1HM1A4zWjJC+I8Y+aKzG5dl+6wNOHHQ4NmG2PEXRJYhujyodFH+wO0dEr4GM1WoaWog8xsYQ6mQJAC0eVpBM96spUB1eMN56+BwlJ4H3Qx4TAvAs";

var reader = new Ber.Reader(new Buffer(pubKeyStr, "base64"));
reader.readSequence();
reader.readSequence();
reader.readOID(); // Hey, I'm an elliptic curve
reader.readOID(); // This contains the curve type, could be useful

// The first byte is unused, it contains the "number of unused bits in last octet"
// The pubKey should start at "04" which signifies it is an "uncompressed" public key.
var pubKey = new Buffer(reader.readString(Ber.BitString, true)).slice(1);

// It'd be better to get this from the curve type OID
var server = crypto.createECDH('secp384r1');
//server.generateKeys();
server.setPrivateKey("oH53xXsdMRt6VbjlUUggn/QTcUQUqOHcvHl+U1jaGAUe8TP9H3XdKeoqSAKrKBGG","base64");
assert(server.computeSecret(pubKey,"binary","base64")=="sM5HvG6efG0RwRe7S+Er9ingxuVzC6HIXmQ1DITVkh4GmX7pboSzbLtaTTNKE8bJ");
```

**Comment by rom1504** [comment]
Nice work @roblabla btw !

**Comment by ghost** [comment]
If github had a +10 button, I'd press it. Fantastic work. Thank you.

**Comment by rom1504** [comment]
I don't think this is quite done.

**Comment by rom1504** [comment]
Well I did all yawkat tests. Except I can't try with the same private key because it doesn't have the same format (or something, it doesn't produce the same result)

**Comment by roblabla** [comment]
Can you link to the test ?

**Comment by rom1504** [comment]
https://github.com/mhsjlw/pocket-minecraft-protocol/tree/realms/test

**Comment by rom1504** [comment]
I was talking about this part : https://github.com/mhsjlw/pocket-minecraft-protocol/blob/realms/test/ecdh_key_exchange.js#L26
they key isn't in the same format as in https://confluence.yawk.at/display/PEPROTOCOL/Encryption (MB8CAQAwEAYHKoZIzj0CAQYFK4EEACIECDAGAgEBBAEB)
I guess it's possible we need to do some messing with it and asn1 if we want to test with that key.

Testing with our key might be ok too though, since it actually works in pmp itself now (see #14 )

**Comment by rom1504** [comment]
ok it works enough
