### ISSUE TITLE
1.0.0.0 support

### ISSUE THREAD

**Issue by ghost** [PrismarineJS/bedrock-protocol#18]
It's not officially released yet, but we should get started (note that some of this info pertains to [node-raknet](https://github.com/mhsjlw/node-raknet))

- [ ] **See: [#18](https://github.com/PrismarineJS/prismarine-nbt/pull/18)**, NBT ([#15](https://github.com/PrismarineJS/prismarine-nbt/issues/15), https://github.com/PrismarineJS/prismarine-nbt) 
- [x] **See: [#22](https://github.com/PrismarineJS/prismarine-chunk/pull/22)**, Chunk format (https://github.com/PrismarineJS/prismarine-chunk)
- [x] Protocol (Requires (?) [#12](https://github.com/ProtoDef-io/ProtoDef/issues/12), https://github.com/mhsjlw/pocket-minecraft-protocol (also see @filfat's fork))

**Comment by filfat** [comment]
Yeah, would prefer to keep this updated than trying to maintain a separate fork.

**Comment by filfat** [comment]
Perhaps we should write a tool to automatically convert [MiNET's protocol.xml](https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Net/MCPE%20Protocol.xml) to the protodef format automatically? That way we'll be able to quite easily support newer protocols without too much work.

**Comment by ghost** [comment]
Already done, https://gist.github.com/mhsjlw/899b2a9c024f2293d794. It needs to be updated though, I'll get to it.

**Comment by filfat** [comment]
@mhsjlw 
I have started updating the script, it doesn't work quite yet since I haven't added all the custom datatypes. https://gist.github.com/filfat/eb6cd08e1e789b5924f7f733babc4a25

**Comment by filfat** [comment]
Alright, I made the above tool into an easy to install npm package https://github.com/filfat/MiNET-protocol-converter
