### ISSUE TITLE
Protodef Bug

### ISSUE THREAD

**Issue by sylv256** [PrismarineJS/bedrock-protocol#24]
I am getting this weird error once I try to use encapsulated packets.
```
Error: Read error for name : 254 is not in the mappings value
```

**Comment by ghost** [comment]
This means that the packet is not defined in the protocol.json file. This has not been updated in a while-- see PrismarineJS/minecraft-data

**Comment by sylv256** [comment]
Okay, I see there is a new protocol.json file and everything. I'll try to manually update it to 1.12.0. (Sorry for not responding. I've been really busy lately)

**Comment by sylv256** [comment]
It appears it's an issue with the node-raknet library. node-raknet doesn't have the `0xfe` packet defined in the encapsulated_packet mappings array, so it fails to parse the packet. Do I have to add `"0xfe": "mcpe"` to the mappings array?

**Comment by sylv256** [comment]
I was correct... Nevermind.

**Comment by rom1504** [comment]
Did you fix it then ?

**Comment by ghost** [comment]
(if so, a PR is welcome)
