### ISSUE TITLE
Please update :)

### ISSUE THREAD

**Issue by Erkam246** [PrismarineJS/bedrock-protocol#25]

**Comment by rom1504** [comment]
blocked by https://github.com/mhsjlw/node-raknet/issues/9

I know how to do it but I have limited time and currently working on update flying squid

If you have more time, feel free to come to https://gitter.im/mhsjlw/pocket-minecraft-protocol?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge and I'll explain what needs to be done
