### ISSUE TITLE
finish 1.16 rewrite

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/bedrock-protocol#34]
see https://github.com/PrismarineJS/pocket-minecraft-protocol/pull/33#issue-573014191 for details

@extremeheat let's put what needs to be done here

**Comment by rom1504** [comment]
(or in more precise issues, that's even better)

**Comment by rom1504** [comment]
@extremeheat can you say what's the status here?

is this only missing examples+doc+API improvements or is there some big missing feature for basic functionality?

**Comment by extremeheat** [comment]
Protocol wise, I think most of the work is done. The remaining things to do are in-game things like implementing movement and inventory logic. 

- [x] Expose a ping api
- [ ] make encryption optional
- [x] make login process use less constants (right now fixed uuids and strings are used in the login process, not a big deal but these can be detected by a server)
- [x] expose an external api identical to mc-protocol 
- [x] examples, tests, docs, etc 
- [x] implement movement/physics 
- [x] make a basic server implementation
- [x] make a basic client implementation
- [ ] implement inventories 

Nothing there aside from movement is really blocking, so we could just jump to implementing into a mineflayer fork as is I think, I'll look at adding it to mineflayer after the movements get fixed.

**Comment by rom1504** [comment]
inventories/movement/physics should not be in this package imo, they should be in something like mineflayer or flying-squid (https://github.com/PrismarineJS/numerous-alpaca)

**Comment by rom1504** [comment]
I think having API doc here would be pretty useful, this package is not usable at the moment without some basic information

**Comment by extremeheat** [comment]
Yeah, they shouldn't be implemented in the protocol, instead I meant they should be functional to use with the protocol (e.g. fixing fields to make them work). Right now it's coupled in example code in #60, but that can start to be moved out soon I think.

Since I think the project has gathered more eyes yeah I think we should really focus on documenting things more.

**Comment by rom1504** [comment]
Sounds like this is done
