### ISSUE TITLE
How to interact with gui

### ISSUE THREAD

**Issue by tungdo0602** [PrismarineJS/bedrock-protocol#412]
![image](https://github.com/PrismarineJS/bedrock-protocol/assets/89498812/376cfc7b-2021-4877-9764-594b87bbe93b)
like this

**Comment by AnyBananaGAME** [comment]
You can use a relay to get a packet that interacts with it then send it

**Comment by tungdo0602** [comment]
> 

can you give me an example to capture all packet?
