### ISSUE TITLE
Connection/login sequence

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/bedrock-protocol#5]
I think you had it @mhsjlw can you put it there ?
So we can make a basic server example and complete createServer (also createClient)

**Comment by rom1504** [comment]
http://wiki.vg/Pocket_Editon_Login

**Comment by rom1504** [comment]
https://gist.github.com/mhsjlw/8f2923d2e64f1052dab29fbcd86b91ab but what we really need are the packets

**Comment by rom1504** [comment]
most of that is done. Not sure what is the chunk format.
Best way to figure this out is to implement the client login sequence I think. (or to look at some server code I guess)

**Comment by rom1504** [comment]
https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/level/format/generic/BaseChunk.php

https://github.com/PocketMine/PocketMine-MP/blob/master/src/pocketmine/level/format/generic/BaseFullChunk.php

**Comment by rom1504** [comment]
figuring out how to run a mcpe server would be useful to test a client. (pocketmine is next to impossible to run)

**Comment by rom1504** [comment]
can try the client at 158.69.224.171 19132

**Comment by rom1504** [comment]
(check mcpe_login packet is getting split the same way as pocketmine split it : compare the buffers, parameters)

**Comment by rom1504** [comment]
https://gist.github.com/rom1504/0da5d70bbb8ac89b2e28c9e57d35da79 dumps for comparison

seems like handling messageIndex is necesarry, https://github.com/mhsjlw/node-raknet/issues/16

**Comment by rom1504** [comment]
splitting fixed.

client dump : https://gist.github.com/rom1504/9c297bfb9aeb0df2ff7665ea590b73c6

**Comment by rom1504** [comment]
the chunks must be sent in a mcpe_batch

**Comment by rom1504** [comment]
reading a batch packet : https://github.com/PocketMine/PocketMine-MP/blob/f82c59bdc4e0af6f1ce41e183f3a4f21e7e72b4e/src/pocketmine/network/Network.php#L211

sending a batch packet to multiple player (actual udp broadcast ?) : https://github.com/PocketMine/PocketMine-MP/blob/f82c59bdc4e0af6f1ce41e183f3a4f21e7e72b4e/src/pocketmine/Server.php#L1759

encoding of a single chunk packet in a batch : https://github.com/PocketMine/PocketMine-MP/blob/f82c59bdc4e0af6f1ce41e183f3a4f21e7e72b4e/src/pocketmine/Player.php#L3508

**Comment by rom1504** [comment]
we need batch handling.

Basically it's used to send several packets at once, compressed.

We should decode it automatically and re-emit the included packets.

**Comment by rom1504** [comment]
batch parsing is done. We need batch sending

more info on the chunk format : http://minecraft.gamepedia.com/Pocket_Edition_level_format#LevelDB_format

**Comment by rom1504** [comment]
that's what we need to do batch sending https://github.com/PocketMine/PocketMine-MP/blob/f82c59bdc4e0af6f1ce41e183f3a4f21e7e72b4e/src/pocketmine/Server.php#L1782

**Comment by rom1504** [comment]
ah it seems the batching is done automatically there https://github.com/PocketMine/PocketMine-MP/blob/f82c59bdc4e0af6f1ce41e183f3a4f21e7e72b4e/src/pocketmine/network/RakLibInterface.php#L212

basically each chunk packet is in one batch.

**Comment by rom1504** [comment]
tried stuff, the client is not accepting the chunks, not exactly sure what is the problem. I don't understand the "layer" (order =1) way the server is supposed to send chunks. (print the chunk_x and chunk_z values)

**Comment by rom1504** [comment]
https://github.com/PocketMine/PocketMine-MP/blob/f82c59bdc4e0af6f1ce41e183f3a4f21e7e72b4e/src/pocketmine/Player.php#L684

**Comment by rom1504** [comment]
> 16:18 <yawkat> what i do is send a movement update, send a chunk radius update with the right radius and then the chunks
> the sequence is MOVE, START_GAME, SET_SPAWN, MOVE, SET_TIME, RESPAWN, wait for radius request, optionally send update for the radius, send chunks in radius, SPAWNED

**Comment by ghost** [comment]
he left out some parts, here is the _complete_ login sequence:
- send a status of 0
- send a move with an entity id of 0
- start game with an entity id of 0
- set spawn position
- move player with entity id of 0
- set time
- send a respawn
- send chunks
- send a status of 3
- set time

**Comment by rom1504** [comment]
Let's keep this open until the server example can spawn player (which we might be able to do by looking at numerous-alpaca code if I understand correctly)

**Comment by rom1504** [comment]
Okay I made it spawn.

Going to leave this issue open a little bit longer until I can actually send a chunk.

**Comment by ghost** [comment]
sounds good

**Comment by rom1504** [comment]
I'm going to try what I pushed a little bit more but basically this should be solved now.

**Comment by rom1504** [comment]
okay working
