### ISSUE TITLE
Size.js doesn't exist

### ISSUE THREAD

**Issue by ScooScoot** [PrismarineJS/bedrock-protocol#55]

**Comment by extremeheat** [comment]
Hi, this is still experimental and a work in progress. There's not much you can do at the moment without prior knowledge of the protocol. The client is the only working part at the moment. The server works too, but it requires additional setup (you need to dump some packets through the proxy example first.)

If you want to test the client, try `npm i extremeheat/bedrock-protocol#new` and use the [client example](https://github.com/extremeheat/bedrock-protocol/blob/new/examples/clientTest.js). 

Some protocol documentation is in https://github.com/extremeheat/bedrock-protocol/blob/new/data/latest/proto.yml, where the serialization code is generated from

**Comment by extremeheat** [comment]
This has been fixed and released, please update
