### ISSUE TITLE
Add some basic missing client, server features

### ISSUE THREAD

**Issue by extremeheat** [PrismarineJS/bedrock-protocol#69]
Features currently missing but in API:

Client API:

version | optional | Version to connect as.(Future feature, see #69) If not specified, should automatically match server version.(Current feature) Defaults to latest version
-- | -- | --

Server API:

kickTimeout | Future | How long to wait before kicking a unresponsive client.
motd | Future | ServerAdvertisment instance. The server advertisment shown to clients, including the message of the day, level name.
-- | -- | --

Some of these go in hand with #35

**Comment by LeonetKenner** [comment]
Finally!!

**Comment by rom1504** [comment]
Is this done?

**Comment by extremeheat** [comment]
Yeah, it's basically done. The kickTimeout part can be implemented by users
