### ISSUE TITLE
Stuck on loading resources when connecting through proxy

### ISSUE THREAD

**Issue by Fihy** [PrismarineJS/bedrock-protocol#82]
Nearly identical proxy configuration to what's in the docs, tested it with 4 servers running different software, loading screen gets stuck on "Loading resource packs"

**Comment by extremeheat** [comment]
Can you add 
```js
process.env.DEBUG = 'minecraft-protocol'
```

to the top of your code and gist.github.com the relevant portion when the proxy starts? Also add `logging: true` to the `Relay` options to print out the packet log.

It's possible this is related to #80.

**Comment by extremeheat** [comment]
Can you check if #83 fixes?

**Comment by Fihy** [comment]
Same problem, I'm also getting disconnected for an invalid skin on other servers as well as timing out.

**Comment by extremeheat** [comment]
Can you provide the debug log ? I’ve tested pocketmine, geyser and we run tests against the vanilla server. Which ones are timing out and/or giving errors? 

Per #11 we do need to do some more tests on CI

**Comment by Fihy** [comment]
Nukkit - Invalid Skin
Cubecraft - Sticking on loading resources 

Logs
https://gist.github.com/Ginyeet/5246bd9eb76c762b7d2ec53b68c8a381

**Comment by Fihy** [comment]
while connecting to Pocketmine and Geyser servers, a large string of seemingly random text is printed to the console and this error is displayed.
Client failed to read packet Error: Checksum mismatch 49f6449415b91a95 != 60a67f4166d083d3
    at Decipheriv.verify (C:\Users\leafr\Desktop\BedrockJS\node_modules\bedrock-protocol\src\transforms\encryption.js:70:13)

**Comment by Fihy** [comment]
Ive reinstalled the protocol via NPM and attempted to connect to Geyser, received this error after finally getting past the loading screen for the first time
https://gist.github.com/Ginyeet/7f64db261ac806af9ed029551f64b357

Edit: 
Tested PM as well, it seems to be working fine.
Edit2:
Upon testing on another PM server I had a similar experience to what happened with the geyser server, an endless string of text was spammed in the console.

After reconnecting a second time to that same server this error was given
https://gist.github.com/Ginyeet/20c8d671cc6d6ab6646e0e76daf76c8b

**Comment by extremeheat** [comment]
The issue with Geyser and PocketMine should be fixed in master now, you can run

```sh
npm i PrismarineJS/bedrock-protocol
```

to get off of master wit npm. Can you see if the issues persist on PocketMine/Geyser afterwards ? Looks like Nukkit validates the skin which we don't send at the moment, that does need to be fixed.

**Comment by Fihy** [comment]
Yup seems to work with pocketmine

**Comment by GameParrot** [comment]
Not fixed
