### ISSUE TITLE
Error when decoding packets when an entity moves

### ISSUE THREAD

**Issue by brokiem** [PrismarineJS/bedrock-protocol#87]
An error occurs when an entity moves (item, mobs, exp orbs, projectile, etc)

buffer: 124b00b3767c4301c7bc42f3bd8543000101
other buffers: 1250008cdb7d433111b2426656834300fbfb , 125a01fc5682430000b04209d7834300e5e5

Update: i got this error when connecting to server with proxy (waterdog)
ReferenceError: Read error for undefined : type1 is not defined

``While decoding 6c000c000676656e69747900000000030120020676656e69747901000000031052616e6b3a20c2a73744656661756c7404067665669747902000000030b43726174653a20c2a76130060676656e69747903000000030b436f696e733a20c2a76130080676656e69747904000000030b4c6576656c3a20c2a761310a0676656e69747905000000030b456c6f3a20c2a7613130300c0676656e697479060000000319536b696c6c2047726f75703a20c2a7385b554e4b4e4f574e5d0e0676656e6974790700000003022020100676656e69747908000000030c4c6f6262793a20c2a7612331120676656e69747909000000030f506c61796572733a20c2a761313630140676656e6974790a0000000303202020160676656e6974790b0000000313c2a7657777772e76656e6974796d632e636f6d``

Error again when  connecting to random server (maybe error with SetScorePacket)
Buffer: 6c000102096f626a65637469766501000000031ac2a765e28c8820c2a736c2a76c416e6e6f756e63656d656e7473

**Comment by extremeheat** [comment]
Which server gives you the Set Score packet error? Do you have a picture of what it looks like under the vanilla client? It does not seem valid to me. The other errors should be fixed with #88.

It's possible you copied it wrong, can you check if the error persists with #88?

**Comment by brokiem** [comment]
Set Score packet error fixed with #88, no more error that i found
