### ISSUE TITLE
It works... Until it doesnt ;-;

### ISSUE THREAD

**Issue by KeemROH-Development** [PrismarineJS/bedrock-protocol#94]
Once I run it it works fine until after I auth I get this error

```
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/wayresearcher/Code/ROHProxy/node_modules/raknet-native/prebuilds/darwin-19-x64/node-raknet.node
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/wayresearcher/Code/ROHProxy/node_modules/raknet-native/prebuilds/darwin-19-x64/node-raknet.node
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

Yes, I believe its because im on mac.

**Comment by extremeheat** [comment]
What mac OS device and version do you have?

**Comment by extremeheat** [comment]
Hi, this should be fixed inside raknet-native. Can you do a fresh install (delete node_modules folder + package-lock.json) to verify? 

At the moment we fallback to the JavaScript implementation if the native one fails to load, but it looks like an interesting situation here where it loads OK but fails starting in the server.
